# name: Build Tauri App (Windows Only)
 on:
   push:
     branches: [ "main", "master" ]
   pull_request:
     branches: [ "main", "master" ]
 jobs:
   build-windows:
     runs-on: windows-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
       - name: Setup Node.js
         uses: actions/setup-node@v4
         with:
           node-version: '20'
       - name: Setup Rust
         uses: dtolnay/rust-toolchain@stable
       - name: Add Windows target
         run: rustup target add x86_64-pc-windows-msvc
       - name: Install Tauri CLI globally
         run: npm install -g @tauri-apps/cli
       - name: Install frontend dependencies
         run: npm install
         working-directory: ./src/Client/Tauri
       - name: Build Tauri application
         run: npm run tauri build
         working-directory: ./src/Client/Tauri
