name: Build Tauri Client

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup Rust (stable)
      uses: dtolnay/rust-toolchain@stable

    - name: Add Windows target
      if: runner.os == 'Windows'
      run: rustup target add x86_64-pc-windows-msvc

    - name: Install Tauri CLI (global)
      run: npm install -g @tauri-apps/cli

    # Frontend: instala deps e build da web app
    - name: Install frontend dependencies
      working-directory: ./src/WebClient
      run: npm ci

    - name: Build frontend
      working-directory: ./src/WebClient
      run: npm run build

    # Opcional: instala deps do projeto Tauri se existir package.json
    - name: Install Tauri project dependencies (if any)
      # Força uso de bash para que os ifs funcionem igual em macOS/Linux/Windows (Windows tem Git Bash)
      shell: bash
      run: |
        if [ -f ./src/client/tauri/package.json ]; then
          echo "Found package.json in ./src/client/tauri -> running npm ci"
          (cd ./src/client/tauri && npm ci)
        elif [ -f ./src/client/tauri/src-tauri/package.json ]; then
          echo "Found package.json in ./src/client/tauri/src-tauri -> running npm ci"
          (cd ./src/client/tauri/src-tauri && npm ci)
        else
          echo "No package.json found under ./src/client/tauri or ./src/client/tauri/src-tauri - skipping npm ci"
        fi

    # Build Tauri: rode dentro da pasta src-tauri onde está tauri.conf.json
    - name: Build Tauri application
      shell: bash
      working-directory: ./src/client/tauri/src-tauri
      run: |
        echo "== CI debug: current directory = $(pwd) =="
        ls -la
        # tauri build executa o beforeBuildCommand do tauri.conf.json
        tauri build

    # Upload artifacts
    - name: Upload Windows Artifact
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: tauri-build-windows
        path: src/client/tauri/src-tauri/target/release/bundle/msi/*.msi

    - name: Upload macOS Artifact
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v4
      with:
        name: tauri-build-macos
        path: src/client/tauri/src-tauri/target/release/bundle/dmg/*.dmg

    - name: Upload Linux Artifact
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: tauri-build-linux
        path: |
          src/client/tauri/src-tauri/target/release/bundle/appimage/*.AppImage
          src/client/tauri/src-tauri/target/release/bundle/deb/*.deb
