name: 'Tauri Build CI'

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - platform: 'macos-13'       # equivalente a Ventura
          args: '--target aarch64-apple-darwin'
        - platform: 'macos-12'       # equivalente a Monterey
          args: '--target x86_64-apple-darwin'
        - platform: 'windows-2022'
          args: '--target x86_64-pc-windows-msvc'
        - platform: 'windows-2019'
          args: '--target i686-pc-windows-msvc'

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin,x86_64-pc-windows-msvc,i686-pc-windows-msvc

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./WebClient

      - name: Build frontend
        run: npm run build
        working-directory: ./WebClient

      - name: Build Tauri application (Development)
        if: startsWith(github.ref, 'refs/heads/')
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: './Client/Tauri'
          args: ${{ matrix.args }}

      # ---------- ADICIONEI ESTES STEPS PARA GERAR/UPLOADER ARTIFACTS ----------
      - name: Find Tauri build artifacts (debug)
        run: |
          echo "Procurando artefatos Tauri em ./Client/Tauri..."
          find ./Client/Tauri -type f -path "*/target/release/bundle/*" -print || true
          find ./Client/Tauri -type f -path "*/target/*/release/bundle/*" -print || true
          find ./Client/Tauri -type f -name "*.exe" -o -name "*.msi" -o -name "*.dmg" -o -name "*.zip" -o -name "*.app" || true

      - name: Upload Tauri build artifacts
        if: success()  # só sobe se o job tiver sucesso
        uses: actions/upload-artifact@v4
        with:
          name: tauri-artifacts-${{ matrix.platform }}
          path: |
            ./Client/Tauri/target/release/bundle/**
            ./Client/Tauri/src-tauri/target/release/bundle/**
            ./Client/Tauri/target/**/release/bundle/**
            ./Client/Tauri/**/target/**/bundle/**
            ./Client/Tauri/**/.cargo/**/target/**/bundle/**

      # -----------------------------------------------------------------------
